sudo apt-get install -y build-essential
sudo apt-get install -y curl
sudo apt-get install -y git # Should be installed from git PPA
sudo apt-get install -y libcurl4-openssl-dev
sudo apt-get install -y libffi-dev
sudo apt-get install -y libpq-dev
sudo apt-get install -y libreadline-dev
sudo apt-get install -y libssl-dev
sudo apt-get install -y libxml2-dev
sudo apt-get install -y libxslt1-dev
sudo apt-get install -y libyaml-dev
sudo apt-get install -y python-software-properties
sudo apt-get install -y silversearcher-ag
sudo apt-get install -y tree
sudo apt-get install -y zlib1g-dev
sudo apt-get install -y zsh
sudo apt-get install -y gstreamer1.0-plugins-base
sudo apt-get install -y gstreamer1.0-tools
sudo apt-get install -y gstreamer1.0-x
sudo apt-get install -y libqt5webkit5-dev
sudo apt-get install -y libsqlite3-dev
sudo apt-get install -y qt5-default
sudo apt-get install -y qtdeclarative5-dev
sudo apt-get install -y sqlite3
sudo apt-get install -y vim
