sudo apt-get install -y build-essential
sudo apt-get install -y curl
sudo apt-get install -y git-core
sudo apt-get install -y libcurl4-openssl-dev
sudo apt-get install -y libffi-dev
sudo apt-get install -y libpq-dev
sudo apt-get install -y libreadline-dev
sudo apt-get install -y libssl-dev
sudo apt-get install -y libxml2-dev
sudo apt-get install -y libxslt1-dev
sudo apt-get install -y libyaml-dev
sudo apt-get install -y python-software-properties
sudo apt-get install -y silversearcher-ag
sudo apt-get install -y tree
sudo apt-get install -y zlib1g-dev
sudo apt-get install -y zsh
